apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demorag
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 2
    volumeSize: 20
    ssh:
      allow: true
      publicKeyName: demorag
