AWSTemplateFormatVersion: '2010-09-09'
Description: Create a secret in AWS Secrets Manager

Resources:
  rMyAppSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: openai-demo
      Description: Secret for openai api key
      SecretString: !Sub |
        {
          "key": ""
        }

  rJWTmyapp:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: jwt_secret-demo
      Description: jwt for my microservice
      SecretString: !Sub |
        {
          "jwt": ""
        }

  rsecretFrontend:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: rag-chatbot-secrets-demo
      Description: secrets for my microservice
      SecretString: !Sub |
        {
          "REACT_APP_TOKEN": "",
          "REACT_APP_API_GENERATE": "",
          "REACT_APP_API_RETRIEVE": "", 
          "REACT_APP_API_IMPROVE": ""
        }

  rsecretrds:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: rds-secrets-demo
      Description: secrets for my rds
      SecretString: !Sub |
        {
          "username": "",
          "password": "",
          "endpoint": ""
        }
