apiVersion: apps/v1
kind: Deployment
metadata:
  name: improve-question-ms
  labels:
    app: improve-question
spec:
  replicas: 1
  selector:
    matchLabels:
      app: improve-question
  template:
    metadata:
      labels:
        app: improve-question
    spec:
      serviceAccountName: rag-bot-sa
      containers:
        - name: improve-question-container
          image: 697289108405.dkr.ecr.us-east-1.amazonaws.com/demorag:improve_question_ms-2
          ports:
            - containerPort: 8001
          env:
            - name: PYTHONPATH
              value: "/app/src"

---
apiVersion: v1
kind: Service
metadata:
  name: improve-question-service
spec:
  type: LoadBalancer
  selector:
    app: improve-question
  ports:
    - port: 8001
      targetPort: 8001
