apiVersion: apps/v1
kind: Deployment
metadata:
  name: generate-answer-ms
  labels:
    app: generate-answer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generate-answer
  template:
    metadata:
      labels:
        app: generate-answer
    spec:
      serviceAccountName: rag-bot-sa
      containers:
        - name: generate-answer-container
          image: 697289108405.dkr.ecr.us-east-1.amazonaws.com/demorag:generate_answer_ms-def
          ports:
            - containerPort: 8003
          env:
            - name: PYTHONPATH
              value: "/app/src"

---
apiVersion: v1
kind: Service
metadata:
  name: generate-answer-service
spec:
  type: LoadBalancer
  selector:
    app: generate-answer
  ports:
    - port: 8003
      targetPort: 8003
