version: '3.9'

services:
  generate_answer_ms:
    build:
      context: ./generate_answer_ms
      dockerfile: ./deployment/Dockerfile.local
    container_name: generate_answer_ms
    ports:
      - "8003:8003"
    env_file:
      - .env

  generate_retrieve_ms:
    build:
      context: ./generate_retrieve_ms
      dockerfile: ./deployment/Dockerfile.local
    container_name: generate_retrieve_ms
    ports:
      - "8002:8002"
    env_file:
      - .env
    
  embed_store_ms:
    build:
      context: ./improve_question_ms
      dockerfile: ./deployment/Dockerfile.local
    container_name: improve_question_ms
    ports:
      - "8001:8001"
    env_file:
      - .env
    
  preprocess_ms:
    build:
      context: ./preprocessing_ms
      dockerfile: ./deployment/Dockerfile.local
    container_name: preprocessing_ms
    ports:
      - "8000:8000"
    env_file:
      - .env
      
networks:
  default:
    name: rag_network
